// YeProfspilka.Frontend/src/ui/Fields/TextField.jsx
import React from 'react'

const TextField = ({
	className = "",
	placeholder,
	...custom
}) => {
	return (
		<input type="text"
			placeholder={placeholder}
			className={`border focus-visible:outline-black focus-visible:border-2 border-black w-full rounded-standart h-12 p-2 pl-4 md:h-14 placeholder:text-black/25 placeholder:font-ukraine ${className}`}
			{...custom}
		/>
	)
}

export default TextField

// YeProfspilka.Admin/src/app/ui/text-field/text-field.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
	selector: 'app-text-field',
	templateUrl: './text-field.component.html',
})
export class TextFieldComponent implements OnInit {
	@Input() type: string = 'text';
	@Input() classStyles: string = '';
	@Input() placeholder: string = '';
	@Input() value: string = '';
	@Input() defaultValue: string = '';
	@Output() valueChange = new EventEmitter<string>();

	constructor() {}

	ngOnInit(): void {}
}

<input [type]="type"
	[ngClass]="['w-full h-12 border border-black text-xl rounded-standart focus-visible:outline-none px-3', classStyles]"
	[placeholder]="placeholder" [defaultValue]="this.defaultValue" [(ngModel)]="value"
	(ngModelChange)="valueChange.emit(value)">
