// YeProfspilka.Admin/src/app/ui/button/button.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
	selector: 'app-button',
	templateUrl: './button.component.html',
})
export class ButtonComponent implements OnInit {
	@Input() disabled: boolean = false;
	@Input() classStyles = '';
	@Input() type: 'primary' | 'secondary' = 'primary';
	@Output() onClick = new EventEmitter();

	constructor() { }

	ngOnInit(): void { }

	styles(): string {
		if (this.type === 'secondary')
			return 'text-black w-fit duration-300 px-4 bg-transparent border-black border rounded-standart text-xl h-12 font-regular enabled:hover:bg-black/10'

		return 'w-full duration-300 h-12 font-regular rounded-standart text-xl bg-primary text-white enabled:hover:bg-primary/80 duration-200 disabled:cursor-not-allowed';
	}
}

<button class="{{ styles() }} {{ classStyles }}" (click)="onClick.emit()" [disabled]="disabled">
	<ng-content></ng-content>
</button>

// YeProfspilka.Frontend/src/ui/Buttons/Button.jsx
import React from 'react';

const Button = ({ children, className = '', ...custom }) => {
	return (
		<button
			className={`w-full h-12 bg-white text-black border border-black text-base font-regular rounded-standart xl:h-14 max-sm:text-sm duration-150 hover:bg-black/10 ${className}`}
			{...custom}
		>
			{children}
		</button>
	);
};

export default Button;
